APP_PLATFORM := android-9
APP_STL := gnustl_static
NDK_TOOLCHAIN_VERSION := 4.9

APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char
APP_LDFLAGS := -latomic

APP_ABI := armeabi


ifeq ($(NDK_DEBUG),1)
  APP_CPPFLAGS += -DDEBUG -DCOCOS2D_DEBUG=1 -DUSE_FILE32API
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG -DUSE_FILE32API
  APP_OPTIM := release
endif
