// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jinshan_platform_prize.proto

#ifndef PROTOBUF_jinshan_5fplatform_5fprize_2eproto__INCLUDED
#define PROTOBUF_jinshan_5fplatform_5fprize_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "goods.pb.h"
// @@protoc_insertion_point(includes)

namespace app {
namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_jinshan_5fplatform_5fprize_2eproto();
void protobuf_AssignDesc_jinshan_5fplatform_5fprize_2eproto();
void protobuf_ShutdownFile_jinshan_5fplatform_5fprize_2eproto();

class JinshanBoxLevelPrizeProto;
class JinshanBoxLevelPrizeConfigProto;

// ===================================================================

class JinshanBoxLevelPrizeProto : public ::google::protobuf::Message {
 public:
  JinshanBoxLevelPrizeProto();
  virtual ~JinshanBoxLevelPrizeProto();

  JinshanBoxLevelPrizeProto(const JinshanBoxLevelPrizeProto& from);

  inline JinshanBoxLevelPrizeProto& operator=(const JinshanBoxLevelPrizeProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JinshanBoxLevelPrizeProto& default_instance();

  void Swap(JinshanBoxLevelPrizeProto* other);

  // implements Message ----------------------------------------------

  JinshanBoxLevelPrizeProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JinshanBoxLevelPrizeProto& from);
  void MergeFrom(const JinshanBoxLevelPrizeProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 level = 1;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 1;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // optional bytes desc = 2;
  inline bool has_desc() const;
  inline void clear_desc();
  static const int kDescFieldNumber = 2;
  inline const ::std::string& desc() const;
  inline void set_desc(const ::std::string& value);
  inline void set_desc(const char* value);
  inline void set_desc(const void* value, size_t size);
  inline ::std::string* mutable_desc();
  inline ::std::string* release_desc();
  inline void set_allocated_desc(::std::string* desc);

  // repeated .app.message.GoodsWrapperProto prize = 3;
  inline int prize_size() const;
  inline void clear_prize();
  static const int kPrizeFieldNumber = 3;
  inline const ::app::message::GoodsWrapperProto& prize(int index) const;
  inline ::app::message::GoodsWrapperProto* mutable_prize(int index);
  inline ::app::message::GoodsWrapperProto* add_prize();
  inline const ::google::protobuf::RepeatedPtrField< ::app::message::GoodsWrapperProto >&
      prize() const;
  inline ::google::protobuf::RepeatedPtrField< ::app::message::GoodsWrapperProto >*
      mutable_prize();

  // @@protoc_insertion_point(class_scope:app.message.JinshanBoxLevelPrizeProto)
 private:
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_desc();
  inline void clear_has_desc();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* desc_;
  ::google::protobuf::RepeatedPtrField< ::app::message::GoodsWrapperProto > prize_;
  ::google::protobuf::int32 level_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_jinshan_5fplatform_5fprize_2eproto();
  friend void protobuf_AssignDesc_jinshan_5fplatform_5fprize_2eproto();
  friend void protobuf_ShutdownFile_jinshan_5fplatform_5fprize_2eproto();

  void InitAsDefaultInstance();
  static JinshanBoxLevelPrizeProto* default_instance_;
};
// -------------------------------------------------------------------

class JinshanBoxLevelPrizeConfigProto : public ::google::protobuf::Message {
 public:
  JinshanBoxLevelPrizeConfigProto();
  virtual ~JinshanBoxLevelPrizeConfigProto();

  JinshanBoxLevelPrizeConfigProto(const JinshanBoxLevelPrizeConfigProto& from);

  inline JinshanBoxLevelPrizeConfigProto& operator=(const JinshanBoxLevelPrizeConfigProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JinshanBoxLevelPrizeConfigProto& default_instance();

  void Swap(JinshanBoxLevelPrizeConfigProto* other);

  // implements Message ----------------------------------------------

  JinshanBoxLevelPrizeConfigProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JinshanBoxLevelPrizeConfigProto& from);
  void MergeFrom(const JinshanBoxLevelPrizeConfigProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .app.message.JinshanBoxLevelPrizeProto prizelist = 1;
  inline int prizelist_size() const;
  inline void clear_prizelist();
  static const int kPrizelistFieldNumber = 1;
  inline const ::app::message::JinshanBoxLevelPrizeProto& prizelist(int index) const;
  inline ::app::message::JinshanBoxLevelPrizeProto* mutable_prizelist(int index);
  inline ::app::message::JinshanBoxLevelPrizeProto* add_prizelist();
  inline const ::google::protobuf::RepeatedPtrField< ::app::message::JinshanBoxLevelPrizeProto >&
      prizelist() const;
  inline ::google::protobuf::RepeatedPtrField< ::app::message::JinshanBoxLevelPrizeProto >*
      mutable_prizelist();

  // @@protoc_insertion_point(class_scope:app.message.JinshanBoxLevelPrizeConfigProto)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::app::message::JinshanBoxLevelPrizeProto > prizelist_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_jinshan_5fplatform_5fprize_2eproto();
  friend void protobuf_AssignDesc_jinshan_5fplatform_5fprize_2eproto();
  friend void protobuf_ShutdownFile_jinshan_5fplatform_5fprize_2eproto();

  void InitAsDefaultInstance();
  static JinshanBoxLevelPrizeConfigProto* default_instance_;
};
// ===================================================================


// ===================================================================

// JinshanBoxLevelPrizeProto

// optional int32 level = 1;
inline bool JinshanBoxLevelPrizeProto::has_level() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JinshanBoxLevelPrizeProto::set_has_level() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JinshanBoxLevelPrizeProto::clear_has_level() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JinshanBoxLevelPrizeProto::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 JinshanBoxLevelPrizeProto::level() const {
  return level_;
}
inline void JinshanBoxLevelPrizeProto::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// optional bytes desc = 2;
inline bool JinshanBoxLevelPrizeProto::has_desc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JinshanBoxLevelPrizeProto::set_has_desc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void JinshanBoxLevelPrizeProto::clear_has_desc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void JinshanBoxLevelPrizeProto::clear_desc() {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    desc_->clear();
  }
  clear_has_desc();
}
inline const ::std::string& JinshanBoxLevelPrizeProto::desc() const {
  return *desc_;
}
inline void JinshanBoxLevelPrizeProto::set_desc(const ::std::string& value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void JinshanBoxLevelPrizeProto::set_desc(const char* value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void JinshanBoxLevelPrizeProto::set_desc(const void* value, size_t size) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* JinshanBoxLevelPrizeProto::mutable_desc() {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  return desc_;
}
inline ::std::string* JinshanBoxLevelPrizeProto::release_desc() {
  clear_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = desc_;
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void JinshanBoxLevelPrizeProto::set_allocated_desc(::std::string* desc) {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    delete desc_;
  }
  if (desc) {
    set_has_desc();
    desc_ = desc;
  } else {
    clear_has_desc();
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .app.message.GoodsWrapperProto prize = 3;
inline int JinshanBoxLevelPrizeProto::prize_size() const {
  return prize_.size();
}
inline void JinshanBoxLevelPrizeProto::clear_prize() {
  prize_.Clear();
}
inline const ::app::message::GoodsWrapperProto& JinshanBoxLevelPrizeProto::prize(int index) const {
  return prize_.Get(index);
}
inline ::app::message::GoodsWrapperProto* JinshanBoxLevelPrizeProto::mutable_prize(int index) {
  return prize_.Mutable(index);
}
inline ::app::message::GoodsWrapperProto* JinshanBoxLevelPrizeProto::add_prize() {
  return prize_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::app::message::GoodsWrapperProto >&
JinshanBoxLevelPrizeProto::prize() const {
  return prize_;
}
inline ::google::protobuf::RepeatedPtrField< ::app::message::GoodsWrapperProto >*
JinshanBoxLevelPrizeProto::mutable_prize() {
  return &prize_;
}

// -------------------------------------------------------------------

// JinshanBoxLevelPrizeConfigProto

// repeated .app.message.JinshanBoxLevelPrizeProto prizelist = 1;
inline int JinshanBoxLevelPrizeConfigProto::prizelist_size() const {
  return prizelist_.size();
}
inline void JinshanBoxLevelPrizeConfigProto::clear_prizelist() {
  prizelist_.Clear();
}
inline const ::app::message::JinshanBoxLevelPrizeProto& JinshanBoxLevelPrizeConfigProto::prizelist(int index) const {
  return prizelist_.Get(index);
}
inline ::app::message::JinshanBoxLevelPrizeProto* JinshanBoxLevelPrizeConfigProto::mutable_prizelist(int index) {
  return prizelist_.Mutable(index);
}
inline ::app::message::JinshanBoxLevelPrizeProto* JinshanBoxLevelPrizeConfigProto::add_prizelist() {
  return prizelist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::app::message::JinshanBoxLevelPrizeProto >&
JinshanBoxLevelPrizeConfigProto::prizelist() const {
  return prizelist_;
}
inline ::google::protobuf::RepeatedPtrField< ::app::message::JinshanBoxLevelPrizeProto >*
JinshanBoxLevelPrizeConfigProto::mutable_prizelist() {
  return &prizelist_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace app

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_jinshan_5fplatform_5fprize_2eproto__INCLUDED
