// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mail.proto

#ifndef PROTOBUF_mail_2eproto__INCLUDED
#define PROTOBUF_mail_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "spritestat.pb.h"
// @@protoc_insertion_point(includes)

namespace app {
namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mail_2eproto();
void protobuf_AssignDesc_mail_2eproto();
void protobuf_ShutdownFile_mail_2eproto();

class MailProto;

// ===================================================================

class MailProto : public ::google::protobuf::Message {
 public:
  MailProto();
  virtual ~MailProto();

  MailProto(const MailProto& from);

  inline MailProto& operator=(const MailProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MailProto& default_instance();

  void Swap(MailProto* other);

  // implements Message ----------------------------------------------

  MailProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MailProto& from);
  void MergeFrom(const MailProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes content = 3;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 3;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const void* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  inline void set_allocated_content(::std::string* content);

  // optional int32 money = 11;
  inline bool has_money() const;
  inline void clear_money();
  static const int kMoneyFieldNumber = 11;
  inline ::google::protobuf::int32 money() const;
  inline void set_money(::google::protobuf::int32 value);

  // optional int32 yuanbao = 12;
  inline bool has_yuanbao() const;
  inline void clear_yuanbao();
  static const int kYuanbaoFieldNumber = 12;
  inline ::google::protobuf::int32 yuanbao() const;
  inline void set_yuanbao(::google::protobuf::int32 value);

  // optional int64 experience = 13;
  inline bool has_experience() const;
  inline void clear_experience();
  static const int kExperienceFieldNumber = 13;
  inline ::google::protobuf::int64 experience() const;
  inline void set_experience(::google::protobuf::int64 value);

  // optional int32 realAir = 14;
  inline bool has_realair() const;
  inline void clear_realair();
  static const int kRealAirFieldNumber = 14;
  inline ::google::protobuf::int32 realair() const;
  inline void set_realair(::google::protobuf::int32 value);

  // repeated bytes goods_static_data = 21;
  inline int goods_static_data_size() const;
  inline void clear_goods_static_data();
  static const int kGoodsStaticDataFieldNumber = 21;
  inline const ::std::string& goods_static_data(int index) const;
  inline ::std::string* mutable_goods_static_data(int index);
  inline void set_goods_static_data(int index, const ::std::string& value);
  inline void set_goods_static_data(int index, const char* value);
  inline void set_goods_static_data(int index, const void* value, size_t size);
  inline ::std::string* add_goods_static_data();
  inline void add_goods_static_data(const ::std::string& value);
  inline void add_goods_static_data(const char* value);
  inline void add_goods_static_data(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& goods_static_data() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_goods_static_data();

  // repeated bytes goods_dynamic_data = 22;
  inline int goods_dynamic_data_size() const;
  inline void clear_goods_dynamic_data();
  static const int kGoodsDynamicDataFieldNumber = 22;
  inline const ::std::string& goods_dynamic_data(int index) const;
  inline ::std::string* mutable_goods_dynamic_data(int index);
  inline void set_goods_dynamic_data(int index, const ::std::string& value);
  inline void set_goods_dynamic_data(int index, const char* value);
  inline void set_goods_dynamic_data(int index, const void* value, size_t size);
  inline ::std::string* add_goods_dynamic_data();
  inline void add_goods_dynamic_data(const ::std::string& value);
  inline void add_goods_dynamic_data(const char* value);
  inline void add_goods_dynamic_data(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& goods_dynamic_data() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_goods_dynamic_data();

  // @@protoc_insertion_point(class_scope:app.message.MailProto)
 private:
  inline void set_has_content();
  inline void clear_has_content();
  inline void set_has_money();
  inline void clear_has_money();
  inline void set_has_yuanbao();
  inline void clear_has_yuanbao();
  inline void set_has_experience();
  inline void clear_has_experience();
  inline void set_has_realair();
  inline void clear_has_realair();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* content_;
  ::google::protobuf::int32 money_;
  ::google::protobuf::int32 yuanbao_;
  ::google::protobuf::int64 experience_;
  ::google::protobuf::RepeatedPtrField< ::std::string> goods_static_data_;
  ::google::protobuf::RepeatedPtrField< ::std::string> goods_dynamic_data_;
  ::google::protobuf::int32 realair_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_mail_2eproto();
  friend void protobuf_AssignDesc_mail_2eproto();
  friend void protobuf_ShutdownFile_mail_2eproto();

  void InitAsDefaultInstance();
  static MailProto* default_instance_;
};
// ===================================================================


// ===================================================================

// MailProto

// optional bytes content = 3;
inline bool MailProto::has_content() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MailProto::set_has_content() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MailProto::clear_has_content() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MailProto::clear_content() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& MailProto::content() const {
  return *content_;
}
inline void MailProto::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void MailProto::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void MailProto::set_content(const void* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MailProto::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  return content_;
}
inline ::std::string* MailProto::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void MailProto::set_allocated_content(::std::string* content) {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (content) {
    set_has_content();
    content_ = content;
  } else {
    clear_has_content();
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 money = 11;
inline bool MailProto::has_money() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MailProto::set_has_money() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MailProto::clear_has_money() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MailProto::clear_money() {
  money_ = 0;
  clear_has_money();
}
inline ::google::protobuf::int32 MailProto::money() const {
  return money_;
}
inline void MailProto::set_money(::google::protobuf::int32 value) {
  set_has_money();
  money_ = value;
}

// optional int32 yuanbao = 12;
inline bool MailProto::has_yuanbao() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MailProto::set_has_yuanbao() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MailProto::clear_has_yuanbao() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MailProto::clear_yuanbao() {
  yuanbao_ = 0;
  clear_has_yuanbao();
}
inline ::google::protobuf::int32 MailProto::yuanbao() const {
  return yuanbao_;
}
inline void MailProto::set_yuanbao(::google::protobuf::int32 value) {
  set_has_yuanbao();
  yuanbao_ = value;
}

// optional int64 experience = 13;
inline bool MailProto::has_experience() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MailProto::set_has_experience() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MailProto::clear_has_experience() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MailProto::clear_experience() {
  experience_ = GOOGLE_LONGLONG(0);
  clear_has_experience();
}
inline ::google::protobuf::int64 MailProto::experience() const {
  return experience_;
}
inline void MailProto::set_experience(::google::protobuf::int64 value) {
  set_has_experience();
  experience_ = value;
}

// optional int32 realAir = 14;
inline bool MailProto::has_realair() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MailProto::set_has_realair() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MailProto::clear_has_realair() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MailProto::clear_realair() {
  realair_ = 0;
  clear_has_realair();
}
inline ::google::protobuf::int32 MailProto::realair() const {
  return realair_;
}
inline void MailProto::set_realair(::google::protobuf::int32 value) {
  set_has_realair();
  realair_ = value;
}

// repeated bytes goods_static_data = 21;
inline int MailProto::goods_static_data_size() const {
  return goods_static_data_.size();
}
inline void MailProto::clear_goods_static_data() {
  goods_static_data_.Clear();
}
inline const ::std::string& MailProto::goods_static_data(int index) const {
  return goods_static_data_.Get(index);
}
inline ::std::string* MailProto::mutable_goods_static_data(int index) {
  return goods_static_data_.Mutable(index);
}
inline void MailProto::set_goods_static_data(int index, const ::std::string& value) {
  goods_static_data_.Mutable(index)->assign(value);
}
inline void MailProto::set_goods_static_data(int index, const char* value) {
  goods_static_data_.Mutable(index)->assign(value);
}
inline void MailProto::set_goods_static_data(int index, const void* value, size_t size) {
  goods_static_data_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MailProto::add_goods_static_data() {
  return goods_static_data_.Add();
}
inline void MailProto::add_goods_static_data(const ::std::string& value) {
  goods_static_data_.Add()->assign(value);
}
inline void MailProto::add_goods_static_data(const char* value) {
  goods_static_data_.Add()->assign(value);
}
inline void MailProto::add_goods_static_data(const void* value, size_t size) {
  goods_static_data_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MailProto::goods_static_data() const {
  return goods_static_data_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MailProto::mutable_goods_static_data() {
  return &goods_static_data_;
}

// repeated bytes goods_dynamic_data = 22;
inline int MailProto::goods_dynamic_data_size() const {
  return goods_dynamic_data_.size();
}
inline void MailProto::clear_goods_dynamic_data() {
  goods_dynamic_data_.Clear();
}
inline const ::std::string& MailProto::goods_dynamic_data(int index) const {
  return goods_dynamic_data_.Get(index);
}
inline ::std::string* MailProto::mutable_goods_dynamic_data(int index) {
  return goods_dynamic_data_.Mutable(index);
}
inline void MailProto::set_goods_dynamic_data(int index, const ::std::string& value) {
  goods_dynamic_data_.Mutable(index)->assign(value);
}
inline void MailProto::set_goods_dynamic_data(int index, const char* value) {
  goods_dynamic_data_.Mutable(index)->assign(value);
}
inline void MailProto::set_goods_dynamic_data(int index, const void* value, size_t size) {
  goods_dynamic_data_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MailProto::add_goods_dynamic_data() {
  return goods_dynamic_data_.Add();
}
inline void MailProto::add_goods_dynamic_data(const ::std::string& value) {
  goods_dynamic_data_.Add()->assign(value);
}
inline void MailProto::add_goods_dynamic_data(const char* value) {
  goods_dynamic_data_.Add()->assign(value);
}
inline void MailProto::add_goods_dynamic_data(const void* value, size_t size) {
  goods_dynamic_data_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MailProto::goods_dynamic_data() const {
  return goods_dynamic_data_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MailProto::mutable_goods_dynamic_data() {
  return &goods_dynamic_data_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace app

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mail_2eproto__INCLUDED
