// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

#ifndef PROTOBUF_shop_2eproto__INCLUDED
#define PROTOBUF_shop_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "goods.pb.h"
// @@protoc_insertion_point(includes)

namespace app {
namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_shop_2eproto();
void protobuf_AssignDesc_shop_2eproto();
void protobuf_ShutdownFile_shop_2eproto();

class ShopProto;
class ShopTabProto;
class ShopGoodsProto;

enum PriceType {
  MONEY = 0,
  LIJIN = 1,
  YUANBAO = 2
};
bool PriceType_IsValid(int value);
const PriceType PriceType_MIN = MONEY;
const PriceType PriceType_MAX = YUANBAO;
const int PriceType_ARRAYSIZE = PriceType_MAX + 1;

const ::google::protobuf::EnumDescriptor* PriceType_descriptor();
inline const ::std::string& PriceType_Name(PriceType value) {
  return ::google::protobuf::internal::NameOfEnum(
    PriceType_descriptor(), value);
}
inline bool PriceType_Parse(
    const ::std::string& name, PriceType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PriceType>(
    PriceType_descriptor(), name, value);
}
// ===================================================================

class ShopProto : public ::google::protobuf::Message {
 public:
  ShopProto();
  virtual ~ShopProto();

  ShopProto(const ShopProto& from);

  inline ShopProto& operator=(const ShopProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ShopProto& default_instance();

  void Swap(ShopProto* other);

  // implements Message ----------------------------------------------

  ShopProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ShopProto& from);
  void MergeFrom(const ShopProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional bytes name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const void* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // repeated .app.message.ShopTabProto tab_list = 3;
  inline int tab_list_size() const;
  inline void clear_tab_list();
  static const int kTabListFieldNumber = 3;
  inline const ::app::message::ShopTabProto& tab_list(int index) const;
  inline ::app::message::ShopTabProto* mutable_tab_list(int index);
  inline ::app::message::ShopTabProto* add_tab_list();
  inline const ::google::protobuf::RepeatedPtrField< ::app::message::ShopTabProto >&
      tab_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::app::message::ShopTabProto >*
      mutable_tab_list();

  // @@protoc_insertion_point(class_scope:app.message.ShopProto)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::app::message::ShopTabProto > tab_list_;
  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_shop_2eproto();
  friend void protobuf_AssignDesc_shop_2eproto();
  friend void protobuf_ShutdownFile_shop_2eproto();

  void InitAsDefaultInstance();
  static ShopProto* default_instance_;
};
// -------------------------------------------------------------------

class ShopTabProto : public ::google::protobuf::Message {
 public:
  ShopTabProto();
  virtual ~ShopTabProto();

  ShopTabProto(const ShopTabProto& from);

  inline ShopTabProto& operator=(const ShopTabProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ShopTabProto& default_instance();

  void Swap(ShopTabProto* other);

  // implements Message ----------------------------------------------

  ShopTabProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ShopTabProto& from);
  void MergeFrom(const ShopTabProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 index = 1;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 1;
  inline ::google::protobuf::int32 index() const;
  inline void set_index(::google::protobuf::int32 value);

  // optional bytes name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const void* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // repeated .app.message.ShopGoodsProto goods_list = 3;
  inline int goods_list_size() const;
  inline void clear_goods_list();
  static const int kGoodsListFieldNumber = 3;
  inline const ::app::message::ShopGoodsProto& goods_list(int index) const;
  inline ::app::message::ShopGoodsProto* mutable_goods_list(int index);
  inline ::app::message::ShopGoodsProto* add_goods_list();
  inline const ::google::protobuf::RepeatedPtrField< ::app::message::ShopGoodsProto >&
      goods_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::app::message::ShopGoodsProto >*
      mutable_goods_list();

  // @@protoc_insertion_point(class_scope:app.message.ShopTabProto)
 private:
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::app::message::ShopGoodsProto > goods_list_;
  ::google::protobuf::int32 index_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_shop_2eproto();
  friend void protobuf_AssignDesc_shop_2eproto();
  friend void protobuf_ShutdownFile_shop_2eproto();

  void InitAsDefaultInstance();
  static ShopTabProto* default_instance_;
};
// -------------------------------------------------------------------

class ShopGoodsProto : public ::google::protobuf::Message {
 public:
  ShopGoodsProto();
  virtual ~ShopGoodsProto();

  ShopGoodsProto(const ShopGoodsProto& from);

  inline ShopGoodsProto& operator=(const ShopGoodsProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ShopGoodsProto& default_instance();

  void Swap(ShopGoodsProto* other);

  // implements Message ----------------------------------------------

  ShopGoodsProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ShopGoodsProto& from);
  void MergeFrom(const ShopGoodsProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes goods_data = 2 [deprecated = true];
  inline bool has_goods_data() const PROTOBUF_DEPRECATED;
  inline void clear_goods_data() PROTOBUF_DEPRECATED;
  static const int kGoodsDataFieldNumber = 2;
  inline const ::std::string& goods_data() const PROTOBUF_DEPRECATED;
  inline void set_goods_data(const ::std::string& value) PROTOBUF_DEPRECATED;
  inline void set_goods_data(const char* value) PROTOBUF_DEPRECATED;
  inline void set_goods_data(const void* value, size_t size) PROTOBUF_DEPRECATED;
  inline ::std::string* mutable_goods_data() PROTOBUF_DEPRECATED;
  inline ::std::string* release_goods_data() PROTOBUF_DEPRECATED;
  inline void set_allocated_goods_data(::std::string* goods_data) PROTOBUF_DEPRECATED;

  // optional .app.message.PriceType price_type = 4;
  inline bool has_price_type() const;
  inline void clear_price_type();
  static const int kPriceTypeFieldNumber = 4;
  inline ::app::message::PriceType price_type() const;
  inline void set_price_type(::app::message::PriceType value);

  // optional int32 price = 5;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 5;
  inline ::google::protobuf::int32 price() const;
  inline void set_price(::google::protobuf::int32 value);

  // optional int64 start_time = 7;
  inline bool has_start_time() const;
  inline void clear_start_time();
  static const int kStartTimeFieldNumber = 7;
  inline ::google::protobuf::int64 start_time() const;
  inline void set_start_time(::google::protobuf::int64 value);

  // optional int64 end_time = 8;
  inline bool has_end_time() const;
  inline void clear_end_time();
  static const int kEndTimeFieldNumber = 8;
  inline ::google::protobuf::int64 end_time() const;
  inline void set_end_time(::google::protobuf::int64 value);

  // optional int32 promotion = 9;
  inline bool has_promotion() const;
  inline void clear_promotion();
  static const int kPromotionFieldNumber = 9;
  inline ::google::protobuf::int32 promotion() const;
  inline void set_promotion(::google::protobuf::int32 value);

  // optional int64 expire_time = 10 [deprecated = true];
  inline bool has_expire_time() const PROTOBUF_DEPRECATED;
  inline void clear_expire_time() PROTOBUF_DEPRECATED;
  static const int kExpireTimeFieldNumber = 10;
  inline ::google::protobuf::int64 expire_time() const PROTOBUF_DEPRECATED;
  inline void set_expire_time(::google::protobuf::int64 value) PROTOBUF_DEPRECATED;

  // optional int32 duration = 11 [deprecated = true];
  inline bool has_duration() const PROTOBUF_DEPRECATED;
  inline void clear_duration() PROTOBUF_DEPRECATED;
  static const int kDurationFieldNumber = 11;
  inline ::google::protobuf::int32 duration() const PROTOBUF_DEPRECATED;
  inline void set_duration(::google::protobuf::int32 value) PROTOBUF_DEPRECATED;

  // optional int32 show_price = 12;
  inline bool has_show_price() const;
  inline void clear_show_price();
  static const int kShowPriceFieldNumber = 12;
  inline ::google::protobuf::int32 show_price() const;
  inline void set_show_price(::google::protobuf::int32 value);

  // optional .app.message.GoodsWrapperProto goods_wrapper = 13;
  inline bool has_goods_wrapper() const;
  inline void clear_goods_wrapper();
  static const int kGoodsWrapperFieldNumber = 13;
  inline const ::app::message::GoodsWrapperProto& goods_wrapper() const;
  inline ::app::message::GoodsWrapperProto* mutable_goods_wrapper();
  inline ::app::message::GoodsWrapperProto* release_goods_wrapper();
  inline void set_allocated_goods_wrapper(::app::message::GoodsWrapperProto* goods_wrapper);

  // optional string desc = 14;
  inline bool has_desc() const;
  inline void clear_desc();
  static const int kDescFieldNumber = 14;
  inline const ::std::string& desc() const;
  inline void set_desc(const ::std::string& value);
  inline void set_desc(const char* value);
  inline void set_desc(const char* value, size_t size);
  inline ::std::string* mutable_desc();
  inline ::std::string* release_desc();
  inline void set_allocated_desc(::std::string* desc);

  // @@protoc_insertion_point(class_scope:app.message.ShopGoodsProto)
 private:
  inline void set_has_goods_data();
  inline void clear_has_goods_data();
  inline void set_has_price_type();
  inline void clear_has_price_type();
  inline void set_has_price();
  inline void clear_has_price();
  inline void set_has_start_time();
  inline void clear_has_start_time();
  inline void set_has_end_time();
  inline void clear_has_end_time();
  inline void set_has_promotion();
  inline void clear_has_promotion();
  inline void set_has_expire_time();
  inline void clear_has_expire_time();
  inline void set_has_duration();
  inline void clear_has_duration();
  inline void set_has_show_price();
  inline void clear_has_show_price();
  inline void set_has_goods_wrapper();
  inline void clear_has_goods_wrapper();
  inline void set_has_desc();
  inline void clear_has_desc();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* goods_data_;
  int price_type_;
  ::google::protobuf::int32 price_;
  ::google::protobuf::int64 start_time_;
  ::google::protobuf::int64 end_time_;
  ::google::protobuf::int64 expire_time_;
  ::google::protobuf::int32 promotion_;
  ::google::protobuf::int32 duration_;
  ::app::message::GoodsWrapperProto* goods_wrapper_;
  ::std::string* desc_;
  ::google::protobuf::int32 show_price_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(11 + 31) / 32];

  friend void  protobuf_AddDesc_shop_2eproto();
  friend void protobuf_AssignDesc_shop_2eproto();
  friend void protobuf_ShutdownFile_shop_2eproto();

  void InitAsDefaultInstance();
  static ShopGoodsProto* default_instance_;
};
// ===================================================================


// ===================================================================

// ShopProto

// optional int32 id = 1;
inline bool ShopProto::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ShopProto::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ShopProto::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ShopProto::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ShopProto::id() const {
  return id_;
}
inline void ShopProto::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional bytes name = 2;
inline bool ShopProto::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ShopProto::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ShopProto::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ShopProto::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& ShopProto::name() const {
  return *name_;
}
inline void ShopProto::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ShopProto::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ShopProto::set_name(const void* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ShopProto::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* ShopProto::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ShopProto::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .app.message.ShopTabProto tab_list = 3;
inline int ShopProto::tab_list_size() const {
  return tab_list_.size();
}
inline void ShopProto::clear_tab_list() {
  tab_list_.Clear();
}
inline const ::app::message::ShopTabProto& ShopProto::tab_list(int index) const {
  return tab_list_.Get(index);
}
inline ::app::message::ShopTabProto* ShopProto::mutable_tab_list(int index) {
  return tab_list_.Mutable(index);
}
inline ::app::message::ShopTabProto* ShopProto::add_tab_list() {
  return tab_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::app::message::ShopTabProto >&
ShopProto::tab_list() const {
  return tab_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::app::message::ShopTabProto >*
ShopProto::mutable_tab_list() {
  return &tab_list_;
}

// -------------------------------------------------------------------

// ShopTabProto

// optional int32 index = 1;
inline bool ShopTabProto::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ShopTabProto::set_has_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ShopTabProto::clear_has_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ShopTabProto::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 ShopTabProto::index() const {
  return index_;
}
inline void ShopTabProto::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
}

// optional bytes name = 2;
inline bool ShopTabProto::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ShopTabProto::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ShopTabProto::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ShopTabProto::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& ShopTabProto::name() const {
  return *name_;
}
inline void ShopTabProto::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ShopTabProto::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ShopTabProto::set_name(const void* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ShopTabProto::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* ShopTabProto::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ShopTabProto::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .app.message.ShopGoodsProto goods_list = 3;
inline int ShopTabProto::goods_list_size() const {
  return goods_list_.size();
}
inline void ShopTabProto::clear_goods_list() {
  goods_list_.Clear();
}
inline const ::app::message::ShopGoodsProto& ShopTabProto::goods_list(int index) const {
  return goods_list_.Get(index);
}
inline ::app::message::ShopGoodsProto* ShopTabProto::mutable_goods_list(int index) {
  return goods_list_.Mutable(index);
}
inline ::app::message::ShopGoodsProto* ShopTabProto::add_goods_list() {
  return goods_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::app::message::ShopGoodsProto >&
ShopTabProto::goods_list() const {
  return goods_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::app::message::ShopGoodsProto >*
ShopTabProto::mutable_goods_list() {
  return &goods_list_;
}

// -------------------------------------------------------------------

// ShopGoodsProto

// optional bytes goods_data = 2 [deprecated = true];
inline bool ShopGoodsProto::has_goods_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ShopGoodsProto::set_has_goods_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ShopGoodsProto::clear_has_goods_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ShopGoodsProto::clear_goods_data() {
  if (goods_data_ != &::google::protobuf::internal::kEmptyString) {
    goods_data_->clear();
  }
  clear_has_goods_data();
}
inline const ::std::string& ShopGoodsProto::goods_data() const {
  return *goods_data_;
}
inline void ShopGoodsProto::set_goods_data(const ::std::string& value) {
  set_has_goods_data();
  if (goods_data_ == &::google::protobuf::internal::kEmptyString) {
    goods_data_ = new ::std::string;
  }
  goods_data_->assign(value);
}
inline void ShopGoodsProto::set_goods_data(const char* value) {
  set_has_goods_data();
  if (goods_data_ == &::google::protobuf::internal::kEmptyString) {
    goods_data_ = new ::std::string;
  }
  goods_data_->assign(value);
}
inline void ShopGoodsProto::set_goods_data(const void* value, size_t size) {
  set_has_goods_data();
  if (goods_data_ == &::google::protobuf::internal::kEmptyString) {
    goods_data_ = new ::std::string;
  }
  goods_data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ShopGoodsProto::mutable_goods_data() {
  set_has_goods_data();
  if (goods_data_ == &::google::protobuf::internal::kEmptyString) {
    goods_data_ = new ::std::string;
  }
  return goods_data_;
}
inline ::std::string* ShopGoodsProto::release_goods_data() {
  clear_has_goods_data();
  if (goods_data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = goods_data_;
    goods_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ShopGoodsProto::set_allocated_goods_data(::std::string* goods_data) {
  if (goods_data_ != &::google::protobuf::internal::kEmptyString) {
    delete goods_data_;
  }
  if (goods_data) {
    set_has_goods_data();
    goods_data_ = goods_data;
  } else {
    clear_has_goods_data();
    goods_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .app.message.PriceType price_type = 4;
inline bool ShopGoodsProto::has_price_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ShopGoodsProto::set_has_price_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ShopGoodsProto::clear_has_price_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ShopGoodsProto::clear_price_type() {
  price_type_ = 0;
  clear_has_price_type();
}
inline ::app::message::PriceType ShopGoodsProto::price_type() const {
  return static_cast< ::app::message::PriceType >(price_type_);
}
inline void ShopGoodsProto::set_price_type(::app::message::PriceType value) {
  assert(::app::message::PriceType_IsValid(value));
  set_has_price_type();
  price_type_ = value;
}

// optional int32 price = 5;
inline bool ShopGoodsProto::has_price() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ShopGoodsProto::set_has_price() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ShopGoodsProto::clear_has_price() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ShopGoodsProto::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline ::google::protobuf::int32 ShopGoodsProto::price() const {
  return price_;
}
inline void ShopGoodsProto::set_price(::google::protobuf::int32 value) {
  set_has_price();
  price_ = value;
}

// optional int64 start_time = 7;
inline bool ShopGoodsProto::has_start_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ShopGoodsProto::set_has_start_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ShopGoodsProto::clear_has_start_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ShopGoodsProto::clear_start_time() {
  start_time_ = GOOGLE_LONGLONG(0);
  clear_has_start_time();
}
inline ::google::protobuf::int64 ShopGoodsProto::start_time() const {
  return start_time_;
}
inline void ShopGoodsProto::set_start_time(::google::protobuf::int64 value) {
  set_has_start_time();
  start_time_ = value;
}

// optional int64 end_time = 8;
inline bool ShopGoodsProto::has_end_time() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ShopGoodsProto::set_has_end_time() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ShopGoodsProto::clear_has_end_time() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ShopGoodsProto::clear_end_time() {
  end_time_ = GOOGLE_LONGLONG(0);
  clear_has_end_time();
}
inline ::google::protobuf::int64 ShopGoodsProto::end_time() const {
  return end_time_;
}
inline void ShopGoodsProto::set_end_time(::google::protobuf::int64 value) {
  set_has_end_time();
  end_time_ = value;
}

// optional int32 promotion = 9;
inline bool ShopGoodsProto::has_promotion() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ShopGoodsProto::set_has_promotion() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ShopGoodsProto::clear_has_promotion() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ShopGoodsProto::clear_promotion() {
  promotion_ = 0;
  clear_has_promotion();
}
inline ::google::protobuf::int32 ShopGoodsProto::promotion() const {
  return promotion_;
}
inline void ShopGoodsProto::set_promotion(::google::protobuf::int32 value) {
  set_has_promotion();
  promotion_ = value;
}

// optional int64 expire_time = 10 [deprecated = true];
inline bool ShopGoodsProto::has_expire_time() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ShopGoodsProto::set_has_expire_time() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ShopGoodsProto::clear_has_expire_time() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ShopGoodsProto::clear_expire_time() {
  expire_time_ = GOOGLE_LONGLONG(0);
  clear_has_expire_time();
}
inline ::google::protobuf::int64 ShopGoodsProto::expire_time() const {
  return expire_time_;
}
inline void ShopGoodsProto::set_expire_time(::google::protobuf::int64 value) {
  set_has_expire_time();
  expire_time_ = value;
}

// optional int32 duration = 11 [deprecated = true];
inline bool ShopGoodsProto::has_duration() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ShopGoodsProto::set_has_duration() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ShopGoodsProto::clear_has_duration() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ShopGoodsProto::clear_duration() {
  duration_ = 0;
  clear_has_duration();
}
inline ::google::protobuf::int32 ShopGoodsProto::duration() const {
  return duration_;
}
inline void ShopGoodsProto::set_duration(::google::protobuf::int32 value) {
  set_has_duration();
  duration_ = value;
}

// optional int32 show_price = 12;
inline bool ShopGoodsProto::has_show_price() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ShopGoodsProto::set_has_show_price() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ShopGoodsProto::clear_has_show_price() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ShopGoodsProto::clear_show_price() {
  show_price_ = 0;
  clear_has_show_price();
}
inline ::google::protobuf::int32 ShopGoodsProto::show_price() const {
  return show_price_;
}
inline void ShopGoodsProto::set_show_price(::google::protobuf::int32 value) {
  set_has_show_price();
  show_price_ = value;
}

// optional .app.message.GoodsWrapperProto goods_wrapper = 13;
inline bool ShopGoodsProto::has_goods_wrapper() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ShopGoodsProto::set_has_goods_wrapper() {
  _has_bits_[0] |= 0x00000200u;
}
inline void ShopGoodsProto::clear_has_goods_wrapper() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void ShopGoodsProto::clear_goods_wrapper() {
  if (goods_wrapper_ != NULL) goods_wrapper_->::app::message::GoodsWrapperProto::Clear();
  clear_has_goods_wrapper();
}
inline const ::app::message::GoodsWrapperProto& ShopGoodsProto::goods_wrapper() const {
  return goods_wrapper_ != NULL ? *goods_wrapper_ : *default_instance_->goods_wrapper_;
}
inline ::app::message::GoodsWrapperProto* ShopGoodsProto::mutable_goods_wrapper() {
  set_has_goods_wrapper();
  if (goods_wrapper_ == NULL) goods_wrapper_ = new ::app::message::GoodsWrapperProto;
  return goods_wrapper_;
}
inline ::app::message::GoodsWrapperProto* ShopGoodsProto::release_goods_wrapper() {
  clear_has_goods_wrapper();
  ::app::message::GoodsWrapperProto* temp = goods_wrapper_;
  goods_wrapper_ = NULL;
  return temp;
}
inline void ShopGoodsProto::set_allocated_goods_wrapper(::app::message::GoodsWrapperProto* goods_wrapper) {
  delete goods_wrapper_;
  goods_wrapper_ = goods_wrapper;
  if (goods_wrapper) {
    set_has_goods_wrapper();
  } else {
    clear_has_goods_wrapper();
  }
}

// optional string desc = 14;
inline bool ShopGoodsProto::has_desc() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void ShopGoodsProto::set_has_desc() {
  _has_bits_[0] |= 0x00000400u;
}
inline void ShopGoodsProto::clear_has_desc() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void ShopGoodsProto::clear_desc() {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    desc_->clear();
  }
  clear_has_desc();
}
inline const ::std::string& ShopGoodsProto::desc() const {
  return *desc_;
}
inline void ShopGoodsProto::set_desc(const ::std::string& value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void ShopGoodsProto::set_desc(const char* value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
}
inline void ShopGoodsProto::set_desc(const char* value, size_t size) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  desc_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ShopGoodsProto::mutable_desc() {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    desc_ = new ::std::string;
  }
  return desc_;
}
inline ::std::string* ShopGoodsProto::release_desc() {
  clear_has_desc();
  if (desc_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = desc_;
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ShopGoodsProto::set_allocated_desc(::std::string* desc) {
  if (desc_ != &::google::protobuf::internal::kEmptyString) {
    delete desc_;
  }
  if (desc) {
    set_has_desc();
    desc_ = desc;
  } else {
    clear_has_desc();
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message
}  // namespace app

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::app::message::PriceType>() {
  return ::app::message::PriceType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_shop_2eproto__INCLUDED
